### PR TITLE
H

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by madhavarshney** [comment]
@neyshahall Just FYI, you've added private information from your `Hangouts.json` into this PR, which means anyone can read that (including emails / names / phone #).

**Comment by Zeegelba** [comment]
I don’t know what that is my kids use this iPad all the time how do I delete it and what is it and does it say? I’m confused


Sent from Yahoo Mail for iPad


On Monday, August 3, 2020, 1:46 PM, Madhav Varshney <notifications@github.com> wrote:




@neyshahall Just FYI, you've added private information from your Hangouts.json into this PR, which means anyone can read that (including emails / names / phone #).

**Comment by madhavarshney** [comment]
Are you (@Zeegelba) and @neyshahall the same person?

**Comment by Zeegelba** [comment]
No I am not in zeegelba I guess my grandson up loaded some file to within and it has all kinds if info I don't even know what it says or is she said it's from hangouts and I don't know what that is either 
    On Tuesday, August 4, 2020, 05:33:26 PM EDT, Madhav Varshney <notifications@github.com> wrote:  
 
 


Are you (@Zeegelba) and @neyshahall the same person?

**Pull request closed without merging**
